include build/make/target/board/generic_arm_ab/BoardConfig.mk
include device/phh/treble/board-base.mk

BOARD_VNDK_VERSION := current
PRODUCT_EXTRA_VNDK_VERSIONS := 27
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE :=
ifeq ($(BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE),)
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1040080896
endif

TARGET_USES_64_BIT_BINDER := false
BOARD_SYSTEMIMAGE_AS_SYSTEM := true
