include build/make/target/board/generic_arm64_ab/BoardConfig.mk
include device/phh/treble/board-base.mk

BOARD_VNDK_VERSION := current
PRODUCT_EXTRA_VNDK_VERSIONS := 27
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE :=
ifeq ($(BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE),)
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1793040384
endif
BOARD_SYSTEMIMAGE_AS_SYSTEM := true
